spring:
  application:
    name: foro_hub
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}